development:
  adapter: postgresql
  encoding: utf8
  database: shop_development
  username: postgres
  password: 123456

test:
  adapter: postgresql
  encoding: utf8
  database: shop_test
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: shop_production
  username: postgres
  password: 123456
